<a href="https://colab.research.google.com/github/davidkevinhh/Orbit-Future-Academy-MSIB/blob/Assesments/Numpy_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy
The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. 

# Creating Arrays

In [1]:
# Import Library NumPy
import numpy as np

# Contoh Membuat Array
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

In [2]:
# Menampilkan Array a
a

array([1, 2, 3])

In [3]:
# Menampilkan Array b
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
# Menampilkan Array c
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Initial Placeholders

In [5]:
# Create an array of zeros
np.zeros((2,3,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [6]:
# Create an array of ones
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
# Create an array of evenly spaced values (step value)
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [8]:
# Create an array of evenly spaced values (number of samples)
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [9]:
# Create a constant array
e = np.full((3,3),7)
e

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [10]:
# Create a 2X2 identity matrix
f = np.eye(3)
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Create an array with random values
np.random.random((2,2))

array([[0.94891726, 0.31845018],
       [0.14942541, 0.79134532]])

In [12]:
# Create an empty array
np.empty((4,2))

array([[0.25, 0.5 ],
       [0.75, 1.  ],
       [1.25, 1.5 ],
       [1.75, 2.  ]])

# Input Output

### Saving & Loading On Disk

In [13]:
# np.save('my_array', a)
# np.savez('array.npz', a, b)
# np.load('my_array.npy')

In [14]:
# np.loadtxt("myfile.txt")
# np.genfromtxt("my_file.csv", delimiter=',')
# np.savetxt("myarray.txt", a, delimiter=" ")

# Data Types

In [15]:
# Signed 64-bit integer types
np.int64

numpy.int64

In [16]:
# Standard double-precision floating point
np.float32

numpy.float32

In [17]:
# Complex numbers represented by 128 floats
np.complex

complex

In [18]:
# Boolean type storing TRUE and FALSE values
np.bool

bool

In [19]:
# Python object type
np.object

object

In [20]:
# Fixed-length string type
np.string_

numpy.bytes_

In [21]:
# Fixed-length unicode type
np.unicode_

numpy.str_

# Inspecting Your Array 

In [22]:
# Array dimensions
a.shape

(3,)

In [23]:
# Length of array
len(a)

3

In [24]:
# Number of array dimensions
b.ndim

2

In [25]:
# Number of array elements
e.size

9

In [26]:
# Data type of array elements
b.dtype

dtype('float64')

In [27]:
# Name of data type
b.dtype.name

'float64'

In [28]:
# Convert an array to a different type
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

# Array Mathematics
## Arithmetic Operations

### Subtraction

In [29]:
# Pengurangan Array - a-b
g = a - b
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [30]:
# Pengurangan Array - a-b
np.subtract(a,b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

### Addition

In [31]:
# Penjumlahan Array - b+a
b + a

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [32]:
# Penjumlahan Array - b+a
np.add(b,a)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

### Division

In [33]:
# Pembagian Array - a/b
a / b

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [34]:
# Pembagian Array - a/b
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

### Multiplication

In [35]:
# Perkalian Array - a*b
a * b

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [36]:
# Perkalian Array - a*b
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

### Exponentiation

In [37]:
# Fungsi eksponensial pada array b
np.exp(b)

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

### Square root

In [38]:
# Fungsi akar pada array b
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### Print sines of an array

In [39]:
# Nilai Sinus pada array a
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

### Element-wise cosine 

In [40]:
# Nilai Cosinus pada array b
np.cos(b)

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

### Element-wise natural logarithm

In [41]:
# Nilai logaritma pada array a
np.log(a)

array([0.        , 0.69314718, 1.09861229])

### Dot product

In [42]:
# Perkalian Titik pada array f
e.dot(f)

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

## Comparison

### Element-wise comparison

In [43]:
# Perbandingan elemen array a==b 
a == b

array([[False,  True,  True],
       [False, False, False]])

In [44]:
# Perbandingan elemen array a<2
a < 2

array([ True, False, False])

### Array-wise comparison

In [45]:
# Perbandingan array a,b
np.array_equal(a, b)

False

## Aggregate Functions

### Array-wise sum

In [46]:
# Agregasi nilai total array a
a.sum()

6

### Array-wise minimum value

In [47]:
# Agregasi nilai minimal array a
a.min()

1

### Maximum value of an array row

In [48]:
# Agregasi nilai maksimal array b
b.max(axis =0)

array([4., 5., 6.])

### Cumulative sum of the elements

In [49]:
# Nilai kumulatif pada array b
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

### Mean

In [50]:
# Nilai Mean array a
a.mean()

2.0

### Median 

In [51]:
# Nilai Median array b
np.median(b)

3.5

### Correlation coefficient

In [52]:
# Nilai korelasi koefisien array a
np.corrcoef(a)

1.0

### Standard deviation

In [53]:
# Nilai standar defiasi array b
np.std(b)

1.5920810978785667

# Copying Arrays

### Create a view of the array with the same data

In [54]:
# Melihat isi array a
h = a.view()
h

array([1, 2, 3])

### Create a copy of the array

In [55]:
# Copy array a
np.copy(a)

array([1, 2, 3])

### Create a deep copy of the array

In [56]:
# Deef copy array a
h = a.copy()
h

array([1, 2, 3])

# Sorting Arrays

### Sort an array

In [57]:
# Mengurutkan array a
a.sort()
a

array([1, 2, 3])

### Sort the elements of an array's axis

In [58]:
# Mengurutkan array c
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

# Subsetting, Slicing, Indexing

## Subsetting

### Select the element at the 2nd index

In [59]:
# Mengambil nilai index ke 2 pada elemen array a
a[2]

3

### Select the element at row 1 column 2 (equivalent to b[1][2])


In [60]:
# Mengambil nilai baris ke 1 kolom ke 2 pada elemen array a
b[1,2]

6.0

## Slicing

### Select items at index 0 and 1

In [61]:
# Mengambil nilai index ke 0 - 1 pada elemen array a
a[0:2]

array([1, 2])

### Select items at rows 0 and 1 in column 1

In [62]:
# Mengambil nilai index ke 0 - 1 kolom ke 1 pada elemen array b
b[0:2,1] 

array([2., 5.])

### Select all items at row 0 (equivalent to b[0:1, :])

In [63]:
# Mengambil semua nilai baris ke 0 pada elemen array b
b[:1]

array([[1.5, 2. , 3. ]])

### Same as [1,:,:]

In [64]:
# Mengambil semua nilai baris ke 1 pada elemen array c
c[1,...]

array([[3., 2., 3.],
       [4., 5., 6.]])

### Reversed array a 

In [65]:
# Mengambil nilai pada elemen array a secara terbalik
a[ : :-1]

array([3, 2, 1])

# Array Manipulation

## Transposing Array

### Permute array dimensions

In [66]:
# Transpose array b
i = np.transpose(b)

In [67]:
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

##  Changing Array Shape

### Flatten the array

In [68]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [69]:
# Meratakan array b menjadi satu dimensi
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

### Reshape, but don’t change data

In [70]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [71]:
# Mengubah array g menjadi 2 dimensi
g.reshape(3,-2)

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

## Adding/Removing Elements

### Return a new array with shape (2,6) 

In [72]:
h

array([1, 2, 3])

In [73]:
# Menambah jumlah elemen array
np.resize(h, (2,6))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

### Append items to an array

In [74]:
h

array([1, 2, 3])

In [75]:
g

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [76]:
# Menambahkan elemen array h dengan array g 
np.append(h,g)

array([ 1. ,  2. ,  3. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

### Insert items in an array

In [77]:
a

array([1, 2, 3])

In [78]:
# Memasukkan nilai 5 index ke 1 dalam array a
np.insert(a, 1, 5)

array([1, 5, 2, 3])

### Delete items from an array

In [79]:
a

array([1, 2, 3])

In [80]:
# Menghapus elemen array a index ke 1
np.delete(a,[1])

array([1, 3])

## Combining Arrays

###  Concatenate arrays

In [81]:
a

array([1, 2, 3])

In [82]:
d

array([10, 15, 20])

In [83]:
# Menggabungkan elemen array a dan d
np.concatenate((a,d),axis=0) 

array([ 1,  2,  3, 10, 15, 20])

### Stack arrays vertically (row-wise)

In [84]:
a

array([1, 2, 3])

In [85]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [86]:
# Susunan array secara vertikal (berdasarkan baris) array a dan b
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Stack arrays vertically (row-wise)

In [87]:
e

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [88]:
f

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
# Susunan array secara vertikal (berdasarkan baris) array e dan f
np.r_[e,f]

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Stack arrays horizontally (column-wise)

In [90]:
# Susunan array secara horizontal (berdasarkan kolom) array e dan f
np.hstack((e,f))

array([[7., 7., 7., 1., 0., 0.],
       [7., 7., 7., 0., 1., 0.],
       [7., 7., 7., 0., 0., 1.]])

### Create stacked column-wise arrays 

In [91]:
a

array([1, 2, 3])

In [92]:
d

array([10, 15, 20])

In [93]:
# Susunan berdasarkan kolom array a dan d
np.column_stack((a,d))

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

### Create stacked column-wise arrays

In [94]:
# Susunan berdasarkan kolom array a dan d
np.c_[a,d]

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

## Splitting Arrays

### Split the array horizontally at the 3rd index

In [95]:
# Memisahkan array a secara horizontal pada indeks ke-3
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

### Split the array vertically at the 2nd index

In [96]:
# Memisahkan array c secara vertikal pada indeks ke-2
np.vsplit(c,2)

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]), array([[[3., 2., 3.],
         [4., 5., 6.]]])]

# Thank You